# https://www.zabbix.com/documentation/current/en/manual/installation/containers

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: zabbix
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - zabbix-net

  zabbix-server:
    image: zabbix/zabbix-server-pgsql:latest
    container_name: zabbix-server
    depends_on:
      - postgres
    environment:
      DB_SERVER_HOST: "postgres"
      POSTGRES_DB: zabbix
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix_pass
      ZBX_TIMEZONE: "Europe/Moscow"
    ports:
      - "10051:10051"
    networks:
      - zabbix-net

  zabbix-web:
    image: zabbix/zabbix-web-nginx-pgsql:latest
    container_name: zabbix-web
    depends_on:
      - postgres
      - zabbix-server
    environment:
      DB_SERVER_HOST: "postgres"
      POSTGRES_DB: zabbix
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix_pass
      ZBX_TIMEZONE: "Europe/Moscow"
      PHP_TZ: "Europe/Moscow"
    ports:
      - "8080:8080"
    networks:
      - zabbix-net

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    depends_on:
      - zabbix-server
    environment:
      GF_SECURITY_ADMIN_PASSWORD: "grafana_pass"
    volumes:
      - grafana_data:/var/lib/grafana
    ports:
      - "3000:3000"
    networks:
      - zabbix-net

networks:
  zabbix-net:
    driver: bridge

volumes:
  postgres_data:
  grafana_data:
